---
- name: Check connectivity
  ping:
    data: alive
  tags: check 

- name: Install packages
  ansible.builtin.dnf:
    pkg:
      - wireshark
      - rstudio-desktop
      - rstudio-server

      - nvidia-utils-515
      - nvidia-driver-515

      - texlive-full

- name: Upgrade dnf packages
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Add flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name:
      # IDEs
      - com.jetbrains.PyCharm-Community
      - com.jetbrains.PyCharm-Professional
      - com.jetbrains.CLion
      - com.visualstudio.code

      # File editors
      - org.blender.Blender
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.libreoffice.LibreOffice
      - org.texstudio.TeXstudio

      # Communication
      - com.discordapp.Discord
      - com.slack.Slack
      - im.pidgin.Pidgin
      - us.zoom.Zoom

      # Citation managers
      - org.zotero.Zotero
      - com.elsevier.MendeleyDesktop

      # Other tools
      - io.github.Qalculate
      - com.bitwarden.desktop
      - com.valvesoftware.Steam

    update_cache: yes
    cache_valid_time: 3600
    state: latest

