---
- name: Install packages
  ansible.builtin.dnf:
    pkg:
      - wireshark
      - rstudio-desktop
      - rstudio-server

      - akmod-nvidia

      - texlive-scheme-full

- name: Upgrade dnf packages
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Add flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name:
      # IDEs
      - com.jetbrains.PyCharm-Community
      - com.jetbrains.PyCharm-Professional
      - com.jetbrains.CLion
      - com.visualstudio.code

      # File editors
      - org.blender.Blender
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.libreoffice.LibreOffice
      - org.texstudio.TeXstudio

      # Communication
      - com.discordapp.Discord
      - com.slack.Slack
      - im.pidgin.Pidgin
      - us.zoom.Zoom

      # Citation managers
      - org.zotero.Zotero
      - com.elsevier.MendeleyDesktop

      # Other tools
      - com.bitwarden.desktop
      - com.spotify.Client
      - com.valvesoftware.Steam
      - io.github.Qalculate
    state: present

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
