---
dependencies:
  - role: common_cli
  - role: conda
  - role: rlang

- name: Check connectivity
  ping:
    data: alive
  tags: check 

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - flatpak
      - software-properties-common
      - dirmngr

      - nvidia-utils-515
      - nvidia-driver-515

      - texlive-full
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt packages
  ansible.builtin.apt:
    name: '*'
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    state: latest

- name: Install flatpak packages
  ansible.builtin.apt:
    name:
      - com.discordapp.Discord
      - com.elsevier.MendeleyDesktop
      - com.slack.Slack
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.libreoffice.LibreOffice
      - org.mozilla.firefox
      - org.zotero.Zotero
      - us.zoom.Zoom

    update_cache: yes
    cache_valid_time: 3600
    state: latest

