---
# A role for installing common ***CLI-only*** tools.
#
- name: Install CLI packages
  ansible.builtin.dnf:
    pkg:
      # multiplexers
      - tmux
      - screen
      - byobu

      # remote management
      - ansible
      - openssh-server

      # system info
      - neofetch
      - htop
      - iotop
      - iftop

      # HTTP clients
      - curl
      - wget
        
      # version control
      - git
      - mercurial
      - subversion

      # misc. tools
      - flatpak
      - '@development-tools'
      - podman-docker
      - docker-compose
      - neovim
      - gromacs
